import type { DropdownConfig } from '@/types';

export const dropdownConfig: DropdownConfig = {
  colleges: [
    'College of Business and Financial Management',
    'College of Computing and Information Sciences',
    'College of Construction Sciences and Engineering',
    'College of Continuing Advanced and Professional Studies',
    'College of Engineering Technology',
    'College of Governance and Public Policy',
    'College of Human Kinetics',
    'College of Innovative Teacher Education',
    'College of Tourism and Hospitality Management',
    'CITE-Higher School ng UMak',
    'Institute of Accountancy',
    'Institute of Arts and Design',
    'Institute of Disaster and Emergency Management',
    'Institutes of Imaging Health Sciences',
    'Institutes of Nursing',
    'Institutes of Pharmacy',
    'Institute of Psychology',
    'Institute of Social Works',
    'School of Law',
    'Other',
  ],
  yearLevels: [
    'Grade 11',
    'Grade 12',
    'First Year level',
    'Second Year level',
    'Third Year level',
    'Fourth Year level',
    'Fifth Year level',
  ],
  minorViolations: [
    'Not wearing ID',
    'Not wearing prescribed school uniform',
    'Wearing of incomplete uniform',
    'Cross Dressing (for gays/lesbians)',
    'Wearing non-prescribed shoes',
    'Wearing of slippers',
    'Wearing of miniskirts and shorts',
    'Make-Up (for males)',
    'Exhibiting rough behavior',
    'Using of vulgar, abusive or obscene language',
    'Loitering',
    'Littering',
    'Careless or unauthorized use of school property',
    'Hair Color',
    'Unauthorized posting of announcements, posters and notices in bulletin boards and the like',
    'Violation of traffic rules along J.P Rizal and inside the campus (Jaywalking)',
    'Male: Earrings, cap inside the classrooms/offices, torn jeans, untidy hair, make-up and cross dressing',
    'Female: Multiple earrings, sleeveless/string blouse, plunging/tube blouse, torn jeans/leggings/jeggings micro mini skirt/short-shorts, heavy make-up/noticeable dyed hair, rubber slippers and cross-dressing',
    'Students shall at all times be neat, clean and decent in their clothing; orderly, respectful, and courteous in their manners & 2.2.2 Students shall refrain from using bad language and from committing acts that are disrespectful. vulgar, or indecent, or which in any manner may cause or tend to disturb other students. faculty members, employees, or officials of the University.',
  ],
  majorViolations: [
    'Vandalism',
    'Plagiarism',
    'Convictions by any court of law',
    'Immoral/and sex-related acts/abortion',
    'Serious physical injury',
    'Thefts of school properties or similar acts',
    'Negligence of Duty',
    'Grave Act of Disrespect and Conduct Unbecoming',
    'Serious Dishonesty and Conduct Unbecoming',
    'Students shall not damage any property of the University',
    'Illegal assembly aggravated by disturbances of the peace and order in the campus',
    'Possession/Distribution (in any form) of pornographic material, sexual objects within the University',
    'Possession of cigarettes and/or smoking within the school premises',
    'Tampering of student\'s ID for the purpose of illegal entry in the University or any place in the school premises',
    'Unauthorized possession of examination materials and documents during examination given by the University',
    'Public Display of Affection - portrayal of untoward behavior which tends to cause sexual excitement or vulgarity',
    'Entering the campus under the influence of wine, liquor, or any intoxicating beverages',
    'Having somebody else take an examination for another (both shall be liable)',
    'Bribing or receiving bribes from faculty members, administrators or non-teaching staff',
    'Misappropriation or embezzlement of organization/class\' fund',
    'Hazing of any kind inflicted on students by another student whether inside or outside the campus',
    'Involvement of any form of attack to another person such as rumble, fist fighting, punching, or armed combat',
    'Carrying or possession of firearms, deadly weapons and explosives within the school premises',
    'Membership/recruitment to any unrecognized association/organization or fraternity/sorority',
    'Unauthorized collection (extortion) of money, checks or other instruments used as University collection purposes',
    'Violation of Dangerous Drug Laws and other similar/related laws',
    'Gross Negligence, Serious Dishonesty and Conduct Unbecoming',
    'Indiscriminate use of all forms of musical instruments, megaphones, cameras, cellular phones, videos, and other game devices during class hours',
    'Portrayal of untoward behavior designed to cause sexual excitement and/or depiction or description of licentiousness or lewdness',
    'Grave act of disrespect that tends to malign the University officials, faculty members or administrative non-teaching staff',
    'Direct physical assault upon students, faculty members, admin or non-teaching staff, or any person of authority in the University',
    'Violation of Anti-Hazing Act of 2018 and/or recruitment of a student to join unrecognized association, organization, fraternity and the like',
    'Showing, exhibiting, display and/or exposing nude or half naked in any of the following forms/modes (1. Print media ; 2. Broadcast ; 3. Others (films, movies, video, tape CDs, DVDs, Blue Ray, Smartphone and the like)',
    'Forging, falsifying or tampering of any academic or official records or documents; making a false statement of any material fact; practicing any deception or fraud in connection with his/her admission, registration, examination, enrolment or graduation',
    'Actions which tend to dishonor, humiliate, embarrass, discredit or contempt, use the name of the University in an unrecognized organization or association, and integrity of the institution, administrator, faculty, staff, employee, and students',
  ],
  otherViolations: [
    'Wearing of t-shirts/blouses, I.D laces, necklace, bracelets, anklet and knuckles with unrecognized fraternities/sororities insignia (Unofficial)',
    'Wearing of Unauthorized Lanyards and the like (Unofficial)',
    'Faculty Evaluation',
    'Faculty Evaluation and Final Permit Application',
    'Faculty Evaluation and UMak-Scan-to-Pay',
    'UMak-Scan-to-Pay/Late Payment',
    'UMak Scan to Pay, Final Permit Application',
    'Final Permit Application',
  ],
  complaintCategories: [
    'Harassment',
    'Payment Issue',
    'Safety Violation',
    'Discrimination',
    'Academic Concern',
    'Facility Issue',
    'Others',
  ],
  gmcPurposes: [
    'CCA Requirement',
    'LANI Scholarship',
    'Admission to other University',
    'Employment Requirement',
    'Scholarship Application',
    'Transfer to other School',
    'Others',
  ],
};

// Contact Information
export const CONTACT_INFO = {
  phone: '8883-1875',
  cellphone: '0995 822 5262',
  email: 'csfd@umak.edu.ph',
  goodMoralEmail: 'csfdgoodmoralcertificate@gmail.com',
  complaintEmail: 'umakpsd.umak.edu.ph',
  website: 'umak.edu.ph/centers/csfd/',
  goodMoralWebsite: 'csfdgoodmoral.umak.edu.ph',
  facebook: '@UMak CSFD',
};

// FAQ Data
export const FAQS = [
  {
    question: 'What is the CSFD?',
    answer: 'The Center for Student Formation and Discipline (CSFD) is a department under the University of Makati that handles student discipline, formation, and welfare matters.',
  },
  {
    question: 'What is the iCSFD Application?',
    answer: 'The iCSFD Application is an online platform that allows students to request documents, file complaints, and access CSFD services digitally.',
  },
  {
    question: 'Who can use the iCSFD Application?',
    answer: 'All currently enrolled UMak students, graduates, and previous students can use the iCSFD Application.',
  },
  {
    question: 'How long does it take for CSFD to review a complaint?',
    answer: 'Complaints are typically reviewed within 3-5 working days. You will receive an email notification once your complaint has been validated.',
  },
  {
    question: 'How do I file a case or complaint?',
    answer: 'You can file a complaint through the iCSFD Application by filling out the Complaint Form with all necessary details and supporting documents.',
  },
  {
    question: 'Is my information kept confidential?',
    answer: 'Yes, all information submitted to CSFD is treated with strict confidentiality in accordance with data privacy laws.',
  },
  {
    question: 'What if my complaint involves a sensitive issue?',
    answer: 'CSFD handles all complaints with sensitivity and professionalism. You may also request to speak with a specific gender staff member if needed.',
  },
  {
    question: 'What should I do if I receive a notice from CSFD?',
    answer: 'Please read the notice carefully and follow the instructions provided. If you have questions, contact CSFD immediately.',
  },
  {
    question: 'Can I bring a guardian or representative?',
    answer: 'Yes, you may bring a guardian or representative, especially for minor students or sensitive cases.',
  },
  {
    question: 'What if I disagree with the resolution?',
    answer: 'You may file an appeal within the specified period stated in the resolution. Contact CSFD for the appeal process.',
  },
  {
    question: 'How do I book an appointment with CSFD?',
    answer: 'You may contact CSFD through the provided phone numbers or email to schedule an appointment.',
  },
  {
    question: 'Can I check my past sessions or logs?',
    answer: 'Yes, you can view your request history and complaint status through your profile in the iCSFD Application.',
  },
  {
    question: 'How does queueing system works?',
    answer: 'CSFD operates on a first-come, first-served basis. Priority is given to urgent matters and scheduled appointments.',
  },
  {
    question: 'What are the operating hours of CSFD?',
    answer: 'CSFD is open from Monday to Friday, 8:00 AM to 5:00 PM.',
  },
  {
    question: 'Who should I contact for help?',
    answer: 'For general concerns, contact csfd@umak.edu.ph. For complaint concerns, contact umakpsd.umak.edu.ph. For good moral certificate concerns, contact csfdgoodmoralcertificate@gmail.com.',
  },
];
